/**
 * A small hand-built ConceptGraph used by tests and dev experiments.
 * The app loads its full graph from src/data/knowledge-base.yaml.
 */

import type { ConceptGraph } from './types';

export const sampleGraph: ConceptGraph = {
  maturityLevels: [
    { id: 'elementary', label: 'Elementary', order: 1, color: '#d9920f', tint: '#fbeccd' },
    { id: 'high-school', label: 'High School', order: 2, color: '#d95f38', tint: '#fadfd2' },
    { id: 'undergraduate', label: 'Undergraduate', order: 3, color: '#8256c8', tint: '#ebe1f9' },
    { id: 'graduate', label: 'Graduate', order: 4, color: '#2f6fc2', tint: '#d9e6f8' },
  ],
  nodes: [
    // -- Arithmetic ----------------------------------------------------------
    {
      id: 'arithmetic',
      label: 'Arithmetic',
      wikipedia: 'Arithmetic',
      description: 'The art of working with numbers: counting, combining, and comparing quantities.',
      isGroup: true,
    },
    {
      id: 'counting',
      label: 'Counting',
      wikipedia: 'Counting',
      description: 'Assigning numbers to collections of things, one by one.',
      parent: 'arithmetic',
      isGroup: false,
      maturityLevel: 'elementary',
    },
    {
      id: 'addition',
      label: 'Addition',
      wikipedia: 'Addition',
      description: 'Combining two quantities into a total.',
      parent: 'arithmetic',
      isGroup: false,
      maturityLevel: 'elementary',
    },
    {
      id: 'multiplication',
      label: 'Multiplication',
      wikipedia: 'Multiplication',
      description: 'Repeated addition; scaling one quantity by another.',
      parent: 'arithmetic',
      isGroup: false,
      maturityLevel: 'elementary',
    },
    {
      id: 'fractions',
      label: 'Fractions',
      wikipedia: 'Fraction',
      description: 'Parts of a whole, written as one integer over another.',
      parent: 'arithmetic',
      isGroup: false,
      maturityLevel: 'elementary',
    },
    // -- Algebra -------------------------------------------------------------
    {
      id: 'algebra',
      label: 'Algebra',
      wikipedia: 'Algebra',
      description: 'Reasoning about unknown quantities with symbols and equations.',
      isGroup: true,
    },
    {
      id: 'variables',
      label: 'Variables',
      wikipedia: 'Variable_(mathematics)',
      description: 'Letters that stand in for unknown or changing numbers.',
      parent: 'algebra',
      isGroup: false,
      maturityLevel: 'elementary',
    },
    {
      id: 'linear-equations',
      label: 'Linear Equations',
      wikipedia: 'Linear_equation',
      description: 'Equations whose graphs are straight lines.',
      parent: 'algebra',
      isGroup: false,
      maturityLevel: 'elementary',
    },
    {
      id: 'quadratic-equations',
      label: 'Quadratic Equations',
      wikipedia: 'Quadratic_equation',
      description: 'Equations involving a squared unknown.',
      parent: 'algebra',
      isGroup: false,
      maturityLevel: 'high-school',
    },
    // -- Geometry ------------------------------------------------------------
    {
      id: 'geometry',
      label: 'Geometry',
      wikipedia: 'Geometry',
      description: 'The study of shape, size, and space.',
      isGroup: true,
    },
    {
      id: 'shapes',
      label: 'Basic Shapes',
      wikipedia: 'Shape',
      description: 'Triangles, circles, squares, and their properties.',
      parent: 'geometry',
      isGroup: false,
      maturityLevel: 'elementary',
    },
    {
      id: 'pythagorean-theorem',
      label: 'Pythagorean Theorem',
      wikipedia: 'Pythagorean_theorem',
      description: 'Relates the sides of a right triangle: a² + b² = c².',
      parent: 'geometry',
      isGroup: false,
      maturityLevel: 'elementary',
    },
    {
      id: 'trigonometry',
      label: 'Trigonometry',
      wikipedia: 'Trigonometry',
      description: 'Ratios of triangle sides as functions of angles.',
      parent: 'geometry',
      isGroup: false,
      maturityLevel: 'high-school',
    },
    // -- Top-level (no parent) ----------------------------------------------
    {
      id: 'functions',
      label: 'Functions',
      wikipedia: 'Function_(mathematics)',
      description: 'Rules that assign each input exactly one output.',
      isGroup: false,
      maturityLevel: 'high-school',
    },
  ],
  edges: [
    { from: 'counting', to: 'addition' },
    { from: 'addition', to: 'multiplication' },
    { from: 'multiplication', to: 'fractions' },
    { from: 'fractions', to: 'variables' },
    { from: 'variables', to: 'linear-equations' },
    { from: 'linear-equations', to: 'quadratic-equations' },
    { from: 'counting', to: 'shapes' },
    { from: 'shapes', to: 'pythagorean-theorem' },
    { from: 'multiplication', to: 'pythagorean-theorem' },
    { from: 'pythagorean-theorem', to: 'trigonometry' },
    { from: 'variables', to: 'functions' },
    { from: 'functions', to: 'trigonometry' },
    { from: 'functions', to: 'quadratic-equations' },
  ],
};
